name: 'ColorRoller - Color Picker'
author: SamGoody
category: Forms
tags: [color, picker, hsv, hsl, hsg]
#docs: http://url.to.docs
demo: http://siteroller.js/projects/colorpicker/demo.php
current: 0.5